-- Seed data for home_page (UPDATE existing row)
UPDATE home_page SET
    -- Hero Section
    hero_title_en = 'Normal sleeps, super dreams',
    hero_title_es = 'Sueños normales, super sueños',
    hero_title_nl = 'Normale slaap, super dromen',
    hero_subtitle_en = 'Raising a heavy fur muff that covered the whole of her lower arm towards the viewer.',
    hero_subtitle_es = 'Levantando un pesado manguito de piel que cubría todo su antebrazo hacia el espectador.',
    hero_subtitle_nl = 'Een zware bontmof opheffend die haar hele onderarm bedekte naar de kijker.',
    hero_button_en = 'Discover More',
    hero_button_es = 'Descubrir Más',
    hero_button_nl = 'Ontdek Meer',
    hero_image = '/images/slider/slide-1.jpg',

    -- About Section
    about_experience_years = '25',
    about_experience_text_en = 'Years of',
    about_experience_text_es = 'Años de',
    about_experience_text_nl = 'Jaar',
    about_experience_highlight_en = 'Experience',
    about_experience_highlight_es = 'Experiencia',
    about_experience_highlight_nl = 'Ervaring',
    about_tag_en = 'We are consulting agency!',
    about_tag_es = '¡Somos una agencia de consultoría!',
    about_tag_nl = 'Wij zijn een adviesbureau!',
    about_title_en = 'We''re interested to share about us',
    about_title_es = 'Estamos interesados en compartir sobre nosotros',
    about_title_nl = 'We willen graag over ons delen',
    about_description_bold_en = 'It wasn''t a dream. His room, a proper human room although little too small, lay peacefully between its four familiar walls.',
    about_description_bold_es = 'No era un sueño. Su habitación, una habitación humana apropiada aunque un poco pequeña, yacía pacíficamente entre sus cuatro paredes familiares.',
    about_description_bold_nl = 'Het was geen droom. Zijn kamer, een echte mensenkamer hoewel iets te klein, lag vredig tussen zijn vier vertrouwde muren.',
    about_description_en = 'Peacefully between its four familiar walls a collection of textile samples lay spread out on the table - Samsa was a travelling salesman and above it there hung a picture that he had recently cut out of an illustrated magazine and housed in a nice, gilded frame. It showed a lady fitted out with a fur hat and fur boa who sat upright, raising a heavy fur muff that covered the whole of her lower arm towards the viewer. Gregor then turned to look out the window.',
    about_description_es = 'Una colección de muestras textiles estaba esparcida sobre la mesa - Samsa era un viajante de comercio y encima colgaba una imagen que había recortado recientemente de una revista ilustrada y enmarcado en un bonito marco dorado. Mostraba a una dama equipada con un sombrero de piel y una boa de piel que estaba sentada erguida, levantando un pesado manguito de piel.',
    about_description_nl = 'Een verzameling textielen lag uitgespreid op de tafel - Samsa was een handelsreiziger en daarboven hing een foto die hij onlangs uit een tijdschrift had geknipt en in een mooi verguld lijstje had gezet.',
    about_phone = '012345645, +6546521145',
    about_image = '/images/about/about-2.jpg',

    -- Testimonial Section
    testimonial_quote_en = 'Lay peacefully between its four familiar walls. A collection of textile samples lay spread out on the table Samsa was a travelling salesman it there hung a picture that he had recently cut out of an',
    testimonial_quote_es = 'Yacía pacíficamente entre sus cuatro paredes familiares. Una colección de muestras textiles estaba esparcida sobre la mesa. Samsa era un viajante de comercio y encima colgaba una imagen que había recortado recientemente.',
    testimonial_quote_nl = 'Lag vredig tussen zijn vier vertrouwde muren. Een verzameling textielen lag uitgespreid op de tafel. Samsa was een handelsreiziger en daarboven hing een foto.',
    testimonial_author = 'Thomas Calvin',

    -- FunFact Section
    funfact_1_number = '25',
    funfact_1_symbol = '+',
    funfact_1_label_en = 'Years of experience',
    funfact_1_label_es = 'Años de experiencia',
    funfact_1_label_nl = 'Jaar ervaring',
    funfact_1_icon = 'flaticon-diamond',

    funfact_2_number = '500',
    funfact_2_symbol = '+',
    funfact_2_label_en = 'Happy clients',
    funfact_2_label_es = 'Clientes felices',
    funfact_2_label_nl = 'Tevreden klanten',
    funfact_2_icon = 'flaticon-happy',

    funfact_3_number = '350',
    funfact_3_symbol = '+',
    funfact_3_label_en = 'Projects done',
    funfact_3_label_es = 'Proyectos realizados',
    funfact_3_label_nl = 'Projecten voltooid',
    funfact_3_icon = 'flaticon-projector',

    funfact_4_number = '50',
    funfact_4_symbol = '+',
    funfact_4_label_en = 'Awards won',
    funfact_4_label_es = 'Premios ganados',
    funfact_4_label_nl = 'Prijzen gewonnen',
    funfact_4_icon = 'flaticon-medal',

    -- Partner/CTA Section
    partner_tag_en = 'Meet up',
    partner_tag_es = 'Conócenos',
    partner_tag_nl = 'Ontmoet ons',
    partner_title_en = 'Need help with a Project?',
    partner_title_es = '¿Necesitas ayuda con un Proyecto?',
    partner_title_nl = 'Hulp nodig bij een Project?',
    partner_description_en = 'Showed a lady fitted out with a fur hat and fur boa who sat upright, raising a heavy fur muff that covered the whole of her lower arm towards the viewer gregor then turned to look around the world.',
    partner_description_es = 'Mostraba a una dama equipada con un sombrero de piel y una boa de piel que estaba sentada erguida, levantando un pesado manguito de piel que cubría todo su antebrazo hacia el espectador.',
    partner_description_nl = 'Toonde een dame uitgerust met een bontmuts die rechtop zat, een zware bontmof opheffend naar de kijker.',
    partner_button_en = 'Get In Touch',
    partner_button_es = 'Contáctanos',
    partner_button_nl = 'Neem Contact Op',

    -- Contact Section
    contact_phone_message_en = 'Don''t hesitate to contact with us. phone: 01245643654',
    contact_phone_message_es = 'No dudes en contactarnos. teléfono: 01245643654',
    contact_phone_message_nl = 'Aarzel niet om contact met ons op te nemen. telefoon: 01245643654',
    contact_tag_en = 'Contact',
    contact_tag_es = 'Contacto',
    contact_tag_nl = 'Contact',
    contact_title_en = 'Request a free consulting',
    contact_title_es = 'Solicita una consulta gratuita',
    contact_title_nl = 'Vraag een gratis adviesgesprek aan',

    -- Blog Section
    blog_tag_en = 'News',
    blog_tag_es = 'Noticias',
    blog_tag_nl = 'Nieuws',
    blog_title_en = 'Latest News & Events',
    blog_title_es = 'Últimas Noticias y Eventos',
    blog_title_nl = 'Laatste Nieuws & Evenementen',
    blog_description_en = 'Showed a lady fitted out with a fur hat and fur boa who sat upright, raising a heavy fur muff that covered the whole of her lower arm towards the viewer gregor then turned to look around the world.',
    blog_description_es = 'Mostraba a una dama equipada con un sombrero de piel y una boa de piel que estaba sentada erguida, levantando un pesado manguito de piel que cubría todo su antebrazo hacia el espectador.',
    blog_description_nl = 'Toonde een dame uitgerust met een bontmuts die rechtop zat, een zware bontmof opheffend naar de kijker.'
WHERE id = 1;

-- Update global_content
UPDATE global_content SET
    nav_home_en = 'Home',
    nav_home_es = 'Inicio',
    nav_home_nl = 'Home',
    nav_services_en = 'Services',
    nav_services_es = 'Servicios',
    nav_services_nl = 'Diensten',
    nav_blog_en = 'Blog',
    nav_blog_es = 'Blog',
    nav_blog_nl = 'Blog',
    nav_contact_en = 'Contact',
    nav_contact_es = 'Contacto',
    nav_contact_nl = 'Contact',

    footer_about_text_en = 'Samsa was a travelling salesman and above it there hung a picture that he had recently cut out of an illustrated magazine and housed.',
    footer_about_text_es = 'Samsa era un viajante de comercio y encima colgaba una imagen que había recortado recientemente de una revista ilustrada.',
    footer_about_text_nl = 'Samsa was een handelsreiziger en daarboven hing een foto die hij onlangs uit een tijdschrift had geknipt.',

    footer_nav_title_en = 'Navigation',
    footer_nav_title_es = 'Navegación',
    footer_nav_title_nl = 'Navigatie',
    footer_contact_title_en = 'Contact Info',
    footer_contact_title_es = 'Información de Contacto',
    footer_contact_title_nl = 'Contactgegevens',

    footer_about_us_en = 'About us',
    footer_about_us_es = 'Sobre nosotros',
    footer_about_us_nl = 'Over ons',
    footer_contact_us_en = 'Contact us',
    footer_contact_us_es = 'Contáctanos',
    footer_contact_us_nl = 'Contact',
    footer_case_studies_en = 'Case Studies',
    footer_case_studies_es = 'Casos de Estudio',
    footer_case_studies_nl = 'Case Studies',
    footer_our_services_en = 'Our Services',
    footer_our_services_es = 'Nuestros Servicios',
    footer_our_services_nl = 'Onze Diensten',

    footer_phone = '+87655285654',
    footer_email = 'jhair@demo.com',
    footer_office_hours_en = 'Office Time: 10AM - 5PM',
    footer_office_hours_es = 'Horario: 10AM - 5PM',
    footer_office_hours_nl = 'Kantooruren: 10:00 - 17:00',

    footer_copyright_en = 'Copyright © 2023 Jhair. All rights reserved.',
    footer_copyright_es = 'Copyright © 2023 Jhair. Todos los derechos reservados.',
    footer_copyright_nl = 'Copyright © 2023 Jhair. Alle rechten voorbehouden.',

    social_facebook = 'https://facebook.com',
    social_twitter = 'https://twitter.com',
    social_linkedin = 'https://linkedin.com',
    social_instagram = 'https://instagram.com',
    social_pinterest = 'https://pinterest.com',

    logo_url = '/images/logo.png'
WHERE id = 1;

-- Update contact_form
UPDATE contact_form SET
    name_placeholder_en = 'Your Name',
    name_placeholder_es = 'Tu Nombre',
    name_placeholder_nl = 'Uw Naam',
    email_placeholder_en = 'Your Email',
    email_placeholder_es = 'Tu Correo',
    email_placeholder_nl = 'Uw E-mail',
    phone_placeholder_en = 'Your Phone',
    phone_placeholder_es = 'Tu Teléfono',
    phone_placeholder_nl = 'Uw Telefoon',
    service_default_en = 'Choose a Service',
    service_default_es = 'Elige un Servicio',
    service_default_nl = 'Kies een Dienst',
    service_option_1_en = 'Tax Management',
    service_option_1_es = 'Gestión Fiscal',
    service_option_1_nl = 'Belastingbeheer',
    service_option_2_en = 'Financial Advices',
    service_option_2_es = 'Asesoría Financiera',
    service_option_2_nl = 'Financieel Advies',
    service_option_3_en = 'Risk Management',
    service_option_3_es = 'Gestión de Riesgos',
    service_option_3_nl = 'Risicobeheer',
    message_placeholder_en = 'Message',
    message_placeholder_es = 'Mensaje',
    message_placeholder_nl = 'Bericht',
    submit_button_en = 'Submit Now',
    submit_button_es = 'Enviar Ahora',
    submit_button_nl = 'Nu Versturen'
WHERE id = 1;

-- Update services_page
UPDATE services_page SET
    page_title_en = 'Our Services',
    page_title_es = 'Nuestros Servicios',
    page_title_nl = 'Onze Diensten',
    page_breadcrumb_en = 'Services',
    page_breadcrumb_es = 'Servicios',
    page_breadcrumb_nl = 'Diensten',
    section_tag_en = 'Services',
    section_tag_es = 'Servicios',
    section_tag_nl = 'Diensten',
    section_title_en = 'Best services',
    section_title_es = 'Mejores servicios',
    section_title_nl = 'Beste diensten',
    section_description_en = 'Showed a lady fitted out with a fur hat and fur boa who sat upright, raising a heavy fur muff that covered the whole of her lower arm towards the viewer. Gregor then turned to look.',
    section_description_es = 'Mostraba a una dama equipada con un sombrero de piel y una boa de piel que estaba sentada erguida, levantando un pesado manguito de piel que cubría todo su antebrazo hacia el espectador.',
    section_description_nl = 'Toonde een dame uitgerust met een bontmuts en bontboa die rechtop zat, een zware bontmof opheffend die haar hele onderarm bedekte naar de kijker.'
WHERE id = 1;

-- Update blog_page
UPDATE blog_page SET
    page_title_en = 'Latest News & Events',
    page_title_es = 'Últimas Noticias y Eventos',
    page_title_nl = 'Laatste Nieuws & Evenementen',
    page_breadcrumb_en = 'Blog',
    page_breadcrumb_es = 'Blog',
    page_breadcrumb_nl = 'Blog',
    read_more_en = 'Read More',
    read_more_es = 'Leer Más',
    read_more_nl = 'Lees Meer',
    comments_suffix_en = 'Comments',
    comments_suffix_es = 'Comentarios',
    comments_suffix_nl = 'Reacties',
    sidebar_search_title_en = 'Search',
    sidebar_search_title_es = 'Buscar',
    sidebar_search_title_nl = 'Zoeken',
    sidebar_search_placeholder_en = 'Search here...',
    sidebar_search_placeholder_es = 'Buscar aquí...',
    sidebar_search_placeholder_nl = 'Zoek hier...',
    sidebar_about_title_en = 'About Us',
    sidebar_about_title_es = 'Sobre Nosotros',
    sidebar_about_title_nl = 'Over Ons',
    sidebar_about_text_en = 'We are a consulting agency dedicated to helping businesses grow.',
    sidebar_about_text_es = 'Somos una agencia de consultoría dedicada a ayudar a las empresas a crecer.',
    sidebar_about_text_nl = 'Wij zijn een adviesbureau dat bedrijven helpt groeien.',
    sidebar_about_link_en = 'Learn More',
    sidebar_about_link_es = 'Saber Más',
    sidebar_about_link_nl = 'Meer Info',
    sidebar_categories_title_en = 'Categories',
    sidebar_categories_title_es = 'Categorías',
    sidebar_categories_title_nl = 'Categorieën',
    sidebar_related_title_en = 'Related Posts',
    sidebar_related_title_es = 'Artículos Relacionados',
    sidebar_related_title_nl = 'Gerelateerde Berichten',
    sidebar_tags_title_en = 'Tags',
    sidebar_tags_title_es = 'Etiquetas',
    sidebar_tags_title_nl = 'Tags'
WHERE id = 1;

-- Update existing services with full content
UPDATE services SET
    description_en = 'Samsa was a travelling salesman and above it there hung a picture that he had recently cut out of an illustrated magazine and.',
    description_es = 'Samsa era un viajante de comercio y encima colgaba una imagen que había recortado recientemente de una revista ilustrada.',
    description_nl = 'Samsa was een handelsreiziger en daarboven hing een foto die hij onlangs uit een tijdschrift had geknipt.',
    section_1_title_en = 'Overview',
    section_1_title_es = 'Descripción General',
    section_1_title_nl = 'Overzicht',
    section_1_content_en = '<p>Our market research services provide comprehensive insights into your target market, helping you make informed business decisions.</p>',
    section_1_content_es = '<p>Nuestros servicios de investigación de mercado proporcionan información completa sobre su mercado objetivo, ayudándole a tomar decisiones comerciales informadas.</p>',
    section_1_content_nl = '<p>Onze marktonderzoeksdiensten bieden uitgebreide inzichten in uw doelmarkt.</p>',
    section_2_title_en = 'Our Approach',
    section_2_title_es = 'Nuestro Enfoque',
    section_2_title_nl = 'Onze Aanpak',
    section_2_content_en = '<p>We use cutting-edge methodologies and tools to gather and analyze market data.</p>',
    section_2_content_es = '<p>Utilizamos metodologías y herramientas de vanguardia para recopilar y analizar datos del mercado.</p>',
    section_2_content_nl = '<p>We gebruiken geavanceerde methodologieën en tools om marktgegevens te verzamelen.</p>',
    section_3_title_en = 'Results',
    section_3_title_es = 'Resultados',
    section_3_title_nl = 'Resultaten',
    section_3_content_en = '<p>Our clients see measurable improvements in their market positioning and business performance.</p>',
    section_3_content_es = '<p>Nuestros clientes ven mejoras medibles en su posicionamiento de mercado y rendimiento empresarial.</p>',
    section_3_content_nl = '<p>Onze klanten zien meetbare verbeteringen in hun marktpositie.</p>',
    image_url = '/images/services/service-1.jpg'
WHERE slug = 'market-research';

UPDATE services SET
    description_en = 'Samsa was a travelling salesman and above it there hung a picture that he had recently cut out of an illustrated magazine and.',
    description_es = 'Samsa era un viajante de comercio y encima colgaba una imagen que había recortado recientemente de una revista ilustrada.',
    description_nl = 'Samsa was een handelsreiziger en daarboven hing een foto die hij onlangs uit een tijdschrift had geknipt.',
    section_1_title_en = 'Overview',
    section_1_title_es = 'Descripción General',
    section_1_title_nl = 'Overzicht',
    section_1_content_en = '<p>Expert financial advisory services to help your business grow and succeed.</p>',
    section_1_content_es = '<p>Servicios de asesoría financiera experta para ayudar a su negocio a crecer y tener éxito.</p>',
    section_1_content_nl = '<p>Deskundige financiële adviesdiensten om uw bedrijf te laten groeien.</p>',
    section_2_title_en = 'Our Approach',
    section_2_title_es = 'Nuestro Enfoque',
    section_2_title_nl = 'Onze Aanpak',
    section_2_content_en = '<p>We analyze your financial situation and create customized strategies.</p>',
    section_2_content_es = '<p>Analizamos su situación financiera y creamos estrategias personalizadas.</p>',
    section_2_content_nl = '<p>We analyseren uw financiële situatie en creëren strategieën op maat.</p>',
    section_3_title_en = 'Results',
    section_3_title_es = 'Resultados',
    section_3_title_nl = 'Resultaten',
    section_3_content_en = '<p>Improved financial performance and sustainable growth for your business.</p>',
    section_3_content_es = '<p>Mejor rendimiento financiero y crecimiento sostenible para su negocio.</p>',
    section_3_content_nl = '<p>Verbeterde financiële prestaties en duurzame groei voor uw bedrijf.</p>',
    image_url = '/images/services/service-2.jpg'
WHERE slug = 'corporate-finance';

UPDATE services SET
    description_en = 'Samsa was a travelling salesman and above it there hung a picture that he had recently cut out of an illustrated magazine and.',
    description_es = 'Samsa era un viajante de comercio y encima colgaba una imagen que había recortado recientemente de una revista ilustrada.',
    description_nl = 'Samsa was een handelsreiziger en daarboven hing een foto die hij onlangs uit een tijdschrift had geknipt.',
    section_1_title_en = 'Overview',
    section_1_title_es = 'Descripción General',
    section_1_title_nl = 'Overzicht',
    section_1_content_en = '<p>Data-driven insights to transform your business operations and decision-making.</p>',
    section_1_content_es = '<p>Información basada en datos para transformar las operaciones de su negocio y la toma de decisiones.</p>',
    section_1_content_nl = '<p>Datagestuurde inzichten om uw bedrijfsvoering te transformeren.</p>',
    section_2_title_en = 'Our Approach',
    section_2_title_es = 'Nuestro Enfoque',
    section_2_title_nl = 'Onze Aanpak',
    section_2_content_en = '<p>We leverage advanced analytics tools and machine learning algorithms.</p>',
    section_2_content_es = '<p>Aprovechamos herramientas de análisis avanzado y algoritmos de aprendizaje automático.</p>',
    section_2_content_nl = '<p>We maken gebruik van geavanceerde analysetools en machine learning-algoritmen.</p>',
    section_3_title_en = 'Results',
    section_3_title_es = 'Resultados',
    section_3_title_nl = 'Resultaten',
    section_3_content_en = '<p>Better business decisions backed by comprehensive data analysis.</p>',
    section_3_content_es = '<p>Mejores decisiones comerciales respaldadas por un análisis de datos completo.</p>',
    section_3_content_nl = '<p>Betere zakelijke beslissingen ondersteund door data-analyse.</p>',
    image_url = '/images/services/service-3.jpg'
WHERE slug = 'advanced-analytics';
